# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: field.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'field.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ield.proto\x12\x05\x66ield\"8\n\nSensorData\x12\x15\n\rsoil_moisture\x18\x01 \x01(\x02\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"-\n\x11IrrigationRequest\x12\x18\n\x10\x64uration_seconds\x18\x01 \x01(\x05\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x0c\x46ieldService\x12/\n\x0eSendSensorData\x12\x11.field.SensorData\x1a\n.field.Ack\x12\x37\n\x0fStartIrrigation\x12\x18.field.IrrigationRequest\x1a\n.field.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'field_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=22
  _globals['_SENSORDATA']._serialized_end=78
  _globals['_IRRIGATIONREQUEST']._serialized_start=80
  _globals['_IRRIGATIONREQUEST']._serialized_end=125
  _globals['_ACK']._serialized_start=127
  _globals['_ACK']._serialized_end=149
  _globals['_FIELDSERVICE']._serialized_start=151
  _globals['_FIELDSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
